version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
        environment:
          - "discovery.type=single-node"
          - "cluster.name=es-translator"
          - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        name: elasticsearch

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt nose

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            nosetests --logging-level=WARNING

      - store_artifacts:
          path: test-reports
          destination: test-reports
