version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.8
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
        environment:
          - "discovery.type=single-node"
          - "cluster.name=es-translator"
          - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        name: elasticsearch
    steps:
      - checkout
      - run:
          name: Add Apertium repository
          command: |
            wget https://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
      - run:
          name: Install Apertium
          command: |
            sudo apt install -f -qq -y apertium-all-dev dpkg-dev fakeroot lintian
      - restore_cache:
          name: Restore virtualenvs from previous builds
          key: virtualenvs-dependencies-cache-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          name: Install Poetry and project's pip packages
          command: |
            export TERM=xterm-256color
            export COLUMNS=150
            curl -sSL https://install.python-poetry.org | python3 -
            make install
      - save_cache:
          name: Save virtualenvs cache for future builds
          key: virtualenvs-dependencies-cache-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ~/.cache/pypoetry/virtualenvs
      - run:
          name: Run tests
          command: |
            make test
